name: İdil Sülo
bio: 'M.Sc. student in Computer Science'
description: Idil's personal website
external-image: true
picture: 'https://raw.githubusercontent.com/idilsulo/idilsulo.github.io/master/img/photo.png'
resume: true
resume-external: false
resume-url: >-
  docs/Idil_Sulo_CV.pdf
url: 'http://idilsulo.github.io'
permalink: '/:title/'
linkedin: idilsulo/en/
github: idilsulo
email: idilsulo@gmail.com
authors:
  idilsulo:
    name: İdil Sülo
    bio: 'M.Sc. student in Computer Science'
    picture: >-
      'https://raw.githubusercontent.com/idilsulo/idilsulo.github.io/master/img/photo.png'
width: normal
about: true
read-time: true
show-tags: true
related: true
show-author: true
animation: true
plugins_dir:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
jekyll-mentions:
  base_url: 'https://github.com'
blog: true
blog-external: true
blog-url: >-
  http://www.codingwoman.com/
