name: İdil Sülo
bio: 'Computer Engineering Student'
description: Idil's website
external-image: true
picture: 'https://pbs.twimg.com/profile_images/1031096504705064960/L8RyvCie_400x400.jpg'
resume: true
resume-external: true
resume-url: >-
  https://drive.google.com/open?id=10dyFFqY7Xt926AA9jr9Gq7aD88MTGgWc
url: 'http://idilsulo.github.io'
permalink: '/:title/'
linkedin: idilsulo
github: idilsulo
email: idilsulo@gmail.com
authors:
  idilsulo:
    name: İdil Sülo
    bio: 'Computer Engineering student'
    picture: >-
      'https://pbs.twimg.com/profile_images/745646155883741184/Ua0T118O_400x400.jpg'
width: normal
about: true
read-time: true
show-tags: true
related: true
show-author: true
animation: true
plugins_dir:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
jekyll-mentions:
  base_url: 'https://github.com'
