# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Idil Sülo
email: idilsulo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Idil, a master's student in Informatics (Computer Science) at <a href="https://www.tum.de/en/">Technical University of Munich (TUM)</a>.
  I previously obtained my bachelor's in Computer Engineering from <a href="https://ceng.metu.edu.tr/">Middle East Technical University (METU)</a>, Ankara. 
  My interests include computer vision and deep learning research. Through my master's degree, I worked on self-supervised vehicle control
  at <a href="https://vision.in.tum.de/">TUM Computer Vision Group</a> under <a href="https://cvg.cit.tum.de/members/cremers">Prof. Daniel Cremers</a>. 
  I completed my master's thesis on zero-shot learning and 3D object part understanding at 
  <a href="https://www.cs.cit.tum.de/en/camp/">TUM CAMP Chair</a> under 
  <a href="https://www.cs.cit.tum.de/camp/members/senior-research-scientists/federico-tombari/">PD Dr. Federico Tombari</a>.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codingwoman
github_username:  idilsulo

user: Idil Sülo
picture: https://raw.githubusercontent.com/idilsulo/idilsulo.github.io/master/img/photo.png'


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: G-HD8XMF7G1E

# minima:
#   skin: dark

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
