name: İdil Sülo
bio: 'Senior Computer Engineering Student'
description: Idil's website
external-image: true
picture: 'https://raw.githubusercontent.com/idilsulo/idilsulo.github.io/master/img/photo.png'
resume: true
resume-external: true
resume-url: >-
  https://drive.google.com/open?id=1qAUmLKFtmyCYb-MeeF0DRMylTuDSfdx7
url: 'http://idilsulo.github.io'
permalink: '/:title/'
linkedin: idilsulo
github: idilsulo
email: idilsulo@gmail.com
authors:
  idilsulo:
    name: İdil Sülo
    bio: 'Computer Engineering student'
    picture: >-
      'https://raw.githubusercontent.com/idilsulo/idilsulo.github.io/master/img/photo.png'
width: normal
about: true
read-time: true
show-tags: true
related: true
show-author: true
animation: true
plugins_dir:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
jekyll-mentions:
  base_url: 'https://github.com'
